#!/usr/bin/env bash
#
# Author: SharkWipf
#
# Copy this file to /etc/libvirt/hooks, make sure it's called "qemu".
# After this file is installed, restart libvirt.
# From now on, you can easily add per-guest qemu hooks.
# Add your hooks in /etc/libvirt/hooks/qemu.d/vm_name/hook_name/state_name.
# For a list of available hooks, please refer to https://www.libvirt.org/hooks.html
#

GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

BASEDIR="$(dirname $0)"

HOOKPATH="$BASEDIR/qemu.d/$GUEST_NAME/$HOOK_NAME/$STATE_NAME"

set -e # If a script exits with an error, we should as well.

LOGFILE="/var/log/libvirt/custom_hooks.log"

# Check if log file exists, if not, create it
if [ ! -f "$LOGFILE" ]; then
    touch "$LOGFILE"
fi

# Ensure the log file is writable
if [ ! -w "$LOGFILE" ]; then
    echo "Error: Log file '$LOGFILE' is not writable."
    exit 1
fi

# Execute hook scripts and log their output
if [ -f "$HOOKPATH" ] && [ -s "$HOOKPATH" ] && [ -x "$HOOKPATH" ]; then
    eval \"$HOOKPATH\" "$@" >> "$LOGFILE" 2>&1
elif [ -d "$HOOKPATH" ]; then
    while read file; do
        # check for null string
        if [ ! -z "$file" ]; then
          eval \"$file\" "$@" >> "$LOGFILE" 2>&1
        fi
    done <<< "$(find -L "$HOOKPATH" -maxdepth 1 -type f -executable -print)"
fi